# 공공용지 취득실적(환매권 행사)

In [1]:
from common import commonFunc as cf
import pandas as pd
import pickle

pd.set_option('display.max_columns', None)
metadata = pd.read_excel("../input/datalake_meta22.xlsx")

SITENAME = "건설사업정보시스템"
DATANAME= "공공용지 취득실적(환매권 행사)"
with open("../input/calsapikey.pickle","rb") as fr:
    APIKEY = pickle.load(fr)

targetData = metadata.loc[metadata.자료명==DATANAME]
targetData

,순서,자료대상,종류,자료명,데이터 종류,작업자명,망 확인필요,수집방법,컬럼명,한글컬럼명,기본키,요청변수,저장폴더,전처리 항목,업데이트주기,서비스키명,URL,서비스키,파라미터,제공방식,데이터타입,참고문서,참고문서타입,주기,비고
30,31,건설사업정보시스템 - 보상,INBOUND,공공용지 취득실적(환매권 행사),WEB,박동주,외부망,openAPI 연계,"환매권 행사 실적 현황 : brpEvnAcrsRpchCnt, brpEvnAcrsRp...","기준년도 환매권행사실적환매건수,기준년도 환매권행사실적환매면적,기준년도 환매권행사실적...","serviceKey,searchSrYr1,searchSrYr2,searchSrYr3","serviceKey,searchSrYr1,searchSrYr2,searchSrYr3...",../output/건설사업정보시스템/공공용지 취득실적(환매권 행사)/selectIo...,-,-,-,https://www.calspia.go.kr/io/openapi/lc/select...,selectIoLcBrpAndEvnStsList.do,serviceKey=&searchSrYr1=&searchSrYr2=&searchSr...,api,json,건설사업정보시스템-보상,Excel,-,NaN

In [2]:
preSetFolder = targetData["저장폴더"].values[0]

preSetFolder

'../output/건설사업정보시스템/공공용지 취득실적(환매권 행사)/selectIoLcBrpAndEvnStsList.csv'

In [3]:
targetData = metadata.loc[metadata.자료명==DATANAME]

##### 파라미터 설정 #####
URL = targetData["URL"].values[0]
SERVICENAME = targetData["서비스키"].values[0]
SERVICENAME = SERVICENAME.split(".")[0]
REQPARAM = targetData["요청변수"].values[0]
REQPARAM = REQPARAM.split(",")
PRIMARYKEY = targetData["기본키"].values[0]

In [4]:
JSONKEY = "detail1"
DUMMY = 0

In [5]:
# 페이지번호 설정
PAGEYN=1
if REQPARAM.count("pageNo") == 0:
    PAGEYN = 0
else:
    PAGEYN = 1
### 기본정보 설정 및 파라미터 설정 ###
PAGEYN

0

In [6]:
newParam = []
mode = 2
if newParam==[]:
    mode=2
    print("{} 정보 new 모드 {} ".format(DATANAME, mode))

공공용지 취득실적(환매권 행사) 정보 new 모드 2

In [7]:
resultDfMerged = pd.DataFrame()

In [8]:
import datetime

currentDateTime = datetime.datetime.now()
date = currentDateTime.date()
endYr = date.strftime("%Y")
endYr

'2022'

In [9]:
# 기준년도 산정
# 2007년 부터 데이터 존재하나, 1990년부터 수행
startYr = "1990"
dateRange = list(map(int,pd.period_range(startYr,endYr,freq='Y').strftime('%Y').tolist()))
# dateRange

In [10]:
resultDf = pd.DataFrame()
pageList = [] # 4/28 추가
APICALL = 0 #4/28 추가
for i  in dateRange:
    print(i)
    BASEPARAM={"serviceKey":APIKEY[0],"searchSrYr1": str(i), "searchSrYr2": str(i-1), "searchSrYr3": str(i-2),"type":"json"}
    scrapyResult = cf.scrapy(URL,SITENAME,DATANAME,SERVICENAME,BASEPARAM,PAGEYN,APIKEY,APICALL, JSONKEY, DUMMY)
    resultDf = scrapyResult[0]
    pageList.append( scrapyResult[1] )
    APICALL = scrapyResult[2]
    if resultDf.empty: # 정상 데이터가 없는 경우
            print("No Data")
    else:
        resultDfMerged = resultDfMerged.append(resultDf)

1990
1 page scraping start apicall iter: 1 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1990', 'searchSrYr2': '1989', 'searchSrYr3': '1988', 'type': 'json'} rows: 10 completed
1991
1 page scraping start apicall iter: 2 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1991', 'searchSrYr2': '1990', 'searchSrYr3': '1989', 'type': 'json'} rows: 10 completed
1992
1 page scraping start apicall iter: 3 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1992', 'searchSrYr2': '1991', 'searchSrYr3': '1990', 'type': 'json'} rows: 10 completed
1993
1 page scraping start apicall iter: 4 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1993', 'searchSrYr2': '1992', 'searchSrYr3': '1991', 'type': 'json'} rows: 10 completed
1994
1 page scraping start apicall iter: 5 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1994', 'searchSrYr2': '1993', 'searchSrYr3': '1992', 'type': 'json'} rows: 10 completed
1995
1 page scraping start apicall iter: 6 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1995', 'searchSrYr2': '1994', 'searchSrYr3': '1993', 'type': 'json'} rows: 10 completed
1996
1 page scraping start apicall iter: 7 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1996', 'searchSrYr2': '1995', 'searchSrYr3': '1994', 'type': 'json'} rows: 10 completed
1997
1 page scraping start apicall iter: 8 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1997', 'searchSrYr2': '1996', 'searchSrYr3': '1995', 'type': 'json'} rows: 10 completed
1998
1 page scraping start apicall iter: 9 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1998', 'searchSrYr2': '1997', 'searchSrYr3': '1996', 'type': 'json'} rows: 10 completed
1999
1 page scraping start apicall iter: 10 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1999', 'searchSrYr2': '1998', 'searchSrYr3': '1997', 'type': 'json'} rows: 10 completed
2000
1 page scraping start apicall iter: 11 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2000', 'searchSrYr2': '1999', 'searchSrYr3': '1998', 'type': 'json'} rows: 10 completed
2001
1 page scraping start apicall iter: 12 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2001', 'searchSrYr2': '2000', 'searchSrYr3': '1999', 'type': 'json'} rows: 10 completed
2002
1 page scraping start apicall iter: 13 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2002', 'searchSrYr2': '2001', 'searchSrYr3': '2000', 'type': 'json'} rows: 10 completed
2003
1 page scraping start apicall iter: 14 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2003', 'searchSrYr2': '2002', 'searchSrYr3': '2001', 'type': 'json'} rows: 10 completed
2004
1 page scraping start apicall iter: 15 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2004', 'searchSrYr2': '2003', 'searchSrYr3': '2002', 'type': 'json'} rows: 10 completed
2005
1 page scraping start apicall iter: 16 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2005', 'searchSrYr2': '2004', 'searchSrYr3': '2003', 'type': 'json'} rows: 10 completed
2006
1 page scraping start apicall iter: 17 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2006', 'searchSrYr2': '2005', 'searchSrYr3': '2004', 'type': 'json'} rows: 10 completed
2007
1 page scraping start apicall iter: 18 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2007', 'searchSrYr2': '2006', 'searchSrYr3': '2005', 'type': 'json'} rows: 10 completed
2008
1 page scraping start apicall iter: 19 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2008', 'searchSrYr2': '2007', 'searchSrYr3': '2006', 'type': 'json'} rows: 10 completed
2009
1 page scraping start apicall iter: 20 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2009', 'searchSrYr2': '2008', 'searchSrYr3': '2007', 'type': 'json'} rows: 10 completed
2010
1 page scraping start apicall iter: 21 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2010', 'searchSrYr2': '2009', 'searchSrYr3': '2008', 'type': 'json'} rows: 10 completed
2011
1 page scraping start apicall iter: 22 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2011', 'searchSrYr2': '2010', 'searchSrYr3': '2009', 'type': 'json'} rows: 10 completed
2012
1 page scraping start apicall iter: 23 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2012', 'searchSrYr2': '2011', 'searchSrYr3': '2010', 'type': 'json'} rows: 10 completed
2013
1 page scraping start apicall iter: 24 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2013', 'searchSrYr2': '2012', 'searchSrYr3': '2011', 'type': 'json'} rows: 10 completed
2014
1 page scraping start apicall iter: 25 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2014', 'searchSrYr2': '2013', 'searchSrYr3': '2012', 'type': 'json'} rows: 10 completed
2015
1 page scraping start apicall iter: 26 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2015', 'searchSrYr2': '2014', 'searchSrYr3': '2013', 'type': 'json'} rows: 10 completed
2016
1 page scraping start apicall iter: 27 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2016', 'searchSrYr2': '2015', 'searchSrYr3': '2014', 'type': 'json'} rows: 10 completed
2017
1 page scraping start apicall iter: 28 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2017', 'searchSrYr2': '2016', 'searchSrYr3': '2015', 'type': 'json'} rows: 10 completed
2018

1 page scraping start apicall iter: 29 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2018', 'searchSrYr2': '2017', 'searchSrYr3': '2016', 'type': 'json'} rows: 10 completed
2019
1 page scraping start apicall iter: 30 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2019', 'searchSrYr2': '2018', 'searchSrYr3': '2017', 'type': 'json'} rows: 10 completed
2020
1 page scraping start apicall iter: 31 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2020', 'searchSrYr2': '2019', 'searchSrYr3': '2018', 'type': 'json'} rows: 10 completed
2021
1 page scraping start apicall iter: 32 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2021', 'searchSrYr2': '2020', 'searchSrYr3': '2019', 'type': 'json'} rows: 10 completed
2022
1 page scraping start apicall iter: 33 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적(환매권 행사), param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2022', 'searchSrYr2': '2021', 'searchSrYr3': '2020', 'type': 'json'} rows: 10 completed

In [11]:
resultDfMerged = resultDfMerged.drop("index", axis = 1)
resultDfMerged

,brpevnacrsrpchcnt,brpevnacrsrpchare,brpevnacrsrpchamt,brpevnacrsrpchcnt1,brpevnacrsrpchare1,brpevnacrsrpchamt1,brpevnacrsrpchcnt2,brpevnacrsrpchare2,brpevnacrsrpchamt2
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,0,0,0,0,0,0,0,0,0
0,258,196470,21818036721,0,0,0,0,0,0
0,273,888789,62583963882,258,196470,21818036721,0,0,0
0,291,199147,32531100298,273,888789,62583963882,258,196470,21818036721
0,241,140896,27729098340,291,199147,32531100298,273,888789,62583963882
0,290,101402,17300220180,241,140896,27729098340,291,199147,32531100298
0,284,17469431,20498138861,290,101402,17300220180,241,140896,27729098340
0,87,102464,16561468648,284,17469431,20498138861,290,101402,17300220180
0,97,130925,19957781482,87,102464,16561468648,284,17469431,20498138861
0,101,8382496,10862696521,97,130925,19957781482,87,102464,16561468648
0,104,76687,6151092062,101,8382496,10862696521,97,130925,19957781482
0,61,18557,3929918330,104,76687,6151092062,101,8382496,10862696521
0,65,11537,5971126649,61,18557,3929918330,104,76687,6151092062
0,103,40107,8759874762,65,11537,5971126649,61,18557,3929918330
0,84,13591,1740780640,103,40107,8759874762,65,11537,5971126649
0,32,3404,362247510,84,13591,1740780640,103,40107,8759874762
0,0,0,0,32,3404,362247510,84,13591,1740780640

In [11]:
cf.savedata(resultDfMerged, SITENAME,DATANAME,SERVICENAME,mode)

공공용지 취득실적(환매권 행사) save compled

In [12]:
resultDfMerged.shape

(33, 9)

In [13]:
# 파라미터 저장 : 요청 키가 없는 API이므로, pageList만 저장

# 기존사용된 파라미터 정보에 추가 파라미터 append 후 저장
# ptlcmnoList = orgParam + ptlcmnoList
# 파라미터 없는경우 ptlcmnoList = []
ptlcmnoList = []
paramList = [ptlcmnoList,pageList]
# # 최종 파라미터 저장
cf.saveparam(paramList, SITENAME,DATANAME,SERVICENAME)