# 공공용지 취득실적(대토보상)

In [1]:
from common import commonFunc as cf
import pandas as pd
pd.set_option('display.max_columns', None)
metadata = pd.read_excel("../input/datalake_meta22.xlsx")

SITENAME = "건설사업정보시스템"
DATANAME= "공공용지 취득실적(대토보상)"
APIKEY = "1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF"

targetData = metadata.loc[metadata.자료명==DATANAME]
targetData

,순서,자료대상,종류,자료명,데이터 종류,작업자명,망 확인필요,수집방법,컬럼명,기본키,요청변수,저장폴더,전처리 항목,업데이트주기,서비스키명,URL,서비스키,파라미터,제공방식,데이터타입,참고문서,참고문서타입,주기,비고
32,33,건설사업정보시스템 - 보상,INBOUND,공공용지 취득실적(대토보상),WEB,박동주,외부망,openAPI 연계,"대토보상 실적 현황 : slaRwAcqAre, slaRwmn, slaRwAcqAre...","serviceKey,searchSrYr1,searchSrYr2,searchSrYr3","serviceKey,searchSrYr1,searchSrYr2,searchSrYr3...",../output/건설사업정보시스템/공공용지 취득실적(대토보상)/selectIoLc...,-,-,-,https://www.calspia.go.kr/io/openapi/lc/select...,selectIoLcSlaRwStsList.do,serviceKey=&searchSrYr1=&searchSrYr2=&searchSr...,api,json,건설사업정보시스템-보상,Excel,-,NaN

In [2]:
preSetFolder = targetData["저장폴더"].values[0]

preSetFolder

'../output/건설사업정보시스템/공공용지 취득실적(대토보상)/selectIoLcSlaRwStsList.csv'

In [3]:
targetData = metadata.loc[metadata.자료명==DATANAME]

##### 파라미터 설정 #####
URL = targetData["URL"].values[0]
SERVICENAME = targetData["서비스키"].values[0]
SERVICENAME = SERVICENAME.split(".")[0]
REQPARAM = targetData["요청변수"].values[0]
REQPARAM = REQPARAM.split(",")
PRIMARYKEY = targetData["기본키"].values[0]

In [4]:
JSONKEY = "detail1"
DUMMY = 0

In [5]:
#### 페이지번호 설정 ###
PAGEYN=1
if REQPARAM.count("pageyn") == 0:
    PAGEYN = 0
else:
    PAGEYN = 1

In [6]:
resultDfMerged = pd.DataFrame()

In [7]:
import datetime

currentDateTime = datetime.datetime.now()
date = currentDateTime.date()
endYr = date.strftime("%Y")
endYr

'2022'

In [8]:
# 기준년도 산정
# 2007년 부터 데이터 존재하나, 1990년부터 수행
startYr = "1990"
dateRange = list(map(int,pd.period_range(startYr,endYr,freq='Y').strftime('%Y').tolist()))
# dateRange

In [9]:
resultDf = pd.DataFrame()
for i  in dateRange:
    print(i)
    BASEPARAM={"serviceKey":APIKEY,"searchSrYr1": str(i), "searchSrYr2": str(i-1), "searchSrYr3": str(i-2),"type":"json"}
    resultDf = cf.scrapy(URL,SITENAME,DATANAME,SERVICENAME,BASEPARAM,PAGEYN, JSONKEY, DUMMY)
    if resultDf.empty: # 정상 데이터가 없는 경우
            print("No Data")
    else:
        resultDfMerged = resultDfMerged.append(resultDf)

1990
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1990', 'searchSrYr2': '1989', 'searchSrYr3': '1988', 'type': 'json'} rows: 7 completed
1991
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1991', 'searchSrYr2': '1990', 'searchSrYr3': '1989', 'type': 'json'} rows: 7 completed
1992
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1992', 'searchSrYr2': '1991', 'searchSrYr3': '1990', 'type': 'json'} rows: 7 completed
1993
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1993', 'searchSrYr2': '1992', 'searchSrYr3': '1991', 'type': 'json'} rows: 7 completed
1994
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1994', 'searchSrYr2': '1993', 'searchSrYr3': '1992', 'type': 'json'} rows: 7 completed
1995
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1995', 'searchSrYr2': '1994', 'searchSrYr3': '1993', 'type': 'json'} rows: 7 completed
1996
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1996', 'searchSrYr2': '1995', 'searchSrYr3': '1994', 'type': 'json'} rows: 7 completed
1997
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1997', 'searchSrYr2': '1996', 'searchSrYr3': '1995', 'type': 'json'} rows: 7 completed
1998
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1998', 'searchSrYr2': '1997', 'searchSrYr3': '1996', 'type': 'json'} rows: 7 completed
1999
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1999', 'searchSrYr2': '1998', 'searchSrYr3': '1997', 'type': 'json'} rows: 7 completed
2000
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2000', 'searchSrYr2': '1999', 'searchSrYr3': '1998', 'type': 'json'} rows: 7 completed
2001
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2001', 'searchSrYr2': '2000', 'searchSrYr3': '1999', 'type': 'json'} rows: 7 completed
2002
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2002', 'searchSrYr2': '2001', 'searchSrYr3': '2000', 'type': 'json'} rows: 7 completed
2003
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2003', 'searchSrYr2': '2002', 'searchSrYr3': '2001', 'type': 'json'} rows: 7 completed
2004
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2004', 'searchSrYr2': '2003', 'searchSrYr3': '2002', 'type': 'json'} rows: 7 completed
2005
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2005', 'searchSrYr2': '2004', 'searchSrYr3': '2003', 'type': 'json'} rows: 7 completed
2006
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2006', 'searchSrYr2': '2005', 'searchSrYr3': '2004', 'type': 'json'} rows: 7 completed
2007
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2007', 'searchSrYr2': '2006', 'searchSrYr3': '2005', 'type': 'json'} rows: 7 completed
2008
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2008', 'searchSrYr2': '2007', 'searchSrYr3': '2006', 'type': 'json'} rows: 7 completed
2009
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2009', 'searchSrYr2': '2008', 'searchSrYr3': '2007', 'type': 'json'} rows: 7 completed
2010
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2010', 'searchSrYr2': '2009', 'searchSrYr3': '2008', 'type': 'json'} rows: 7 completed
2011
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2011', 'searchSrYr2': '2010', 'searchSrYr3': '2009', 'type': 'json'} rows: 7 completed
2012
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2012', 'searchSrYr2': '2011', 'searchSrYr3': '2010', 'type': 'json'} rows: 7 completed
2013
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2013', 'searchSrYr2': '2012', 'searchSrYr3': '2011', 'type': 'json'} rows: 7 completed
2014
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2014', 'searchSrYr2': '2013', 'searchSrYr3': '2012', 'type': 'json'} rows: 7 completed
2015
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2015', 'searchSrYr2': '2014', 'searchSrYr3': '2013', 'type': 'json'} rows: 7 completed
2016
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2016', 'searchSrYr2': '2015', 'searchSrYr3': '2014', 'type': 'json'} rows: 7 completed
2017
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2017', 'searchSrYr2': '2016', 'searchSrYr3': '2015', 'type': 'json'} rows: 7 completed
2018
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2018', 'searchSrYr2': '2017', 'searchSrYr3': '2016', 'type': 'json'} rows: 7 completed
2019
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2019', 'searchSrYr2': '2018', 'searchSrYr3': '2017', 'type': 'json'} rows: 7 completed
2020
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2020', 'searchSrYr2': '2019', 'searchSrYr3': '2018', 'type': 'json'} rows: 7 completed
2021
1 page scraping start

Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2021', 'searchSrYr2': '2020', 'searchSrYr3': '2019', 'type': 'json'} rows: 7 completed
2022
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적(대토보상), param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2022', 'searchSrYr2': '2021', 'searchSrYr3': '2020', 'type': 'json'} rows: 7 completed

In [10]:
resultDfMerged = resultDfMerged.drop("index", axis = 1)
resultDfMerged

,slarwacqare,slarwmn,slarwacqare1,slarwmn1,slarwacqare2,slarwmn2
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,0,0,0,0,0,0
0,83408,25092619137,0,0,0,0
0,1491796,204247887071,83408,25092619137,0,0
0,641918,298179051365,1491796,204247887071,83408,25092619137
0,624054,194870746120,641918,298179051365,1491796,204247887071
0,446783,78940073551,624054,194870746120,641918,298179051365
0,133394,111184020292,446783,78940073551,624054,194870746120
0,211924,32799465610,133394,111184020292,446783,78940073551
0,330860,66806061390,211924,32799465610,133394,111184020292
0,488428,253912901470,330860,66806061390,211924,32799465610
0,277135,141870246038,488428,253912901470,330860,66806061390
0,168411,94948298040,277135,141870246038,488428,253912901470
0,515397,407895257450,168411,94948298040,277135,141870246038
0,126242,107298687290,515397,407895257450,168411,94948298040
0,895306,935788021420,126242,107298687290,515397,407895257450
0,850635,790904334760,895306,935788021420,126242,107298687290
0,0,0,850635,790904334760,895306,935788021420

In [11]:
cf.savedata(resultDfMerged, SITENAME,DATANAME,SERVICENAME)

공공용지 취득실적(대토보상) save compled

In [12]:
resultDfMerged.shape

(33, 6)