# 공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황

In [1]:
from common import commonFunc as cf
import pandas as pd
import pickle

pd.set_option('display.max_columns', None)
metadata = pd.read_excel("../input/datalake_meta22.xlsx")

SITENAME = "건설사업정보시스템"
DATANAME= "공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황"
with open("../input/calsapikey.pickle","rb") as fr:
    APIKEY = pickle.load(fr)
targetData = metadata.loc[metadata.자료명==DATANAME]
preSetFolder = targetData["저장폴더"].values[0]

preSetFolder

'../output/건설사업정보시스템/공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황/selectIoLcOrByAreAndRwList.csv'

In [2]:
targetData = metadata.loc[metadata.자료명==DATANAME]

##### 파라미터 설정 #####
URL = targetData["URL"].values[0]
SERVICENAME = targetData["서비스키"].values[0]
SERVICENAME = SERVICENAME.split(".")[0]
REQPARAM = targetData["요청변수"].values[0]
REQPARAM = REQPARAM.split(",")
PRIMARYKEY = targetData["기본키"].values[0]

In [3]:
JSONKEY = "items"
DUMMY = 0

In [4]:
# 페이지번호 설정
PAGEYN=1
if REQPARAM.count("pageNo") == 0:
    PAGEYN = 0
else:
    PAGEYN = 1
### 기본정보 설정 및 파라미터 설정 ###
PAGEYN

0

In [5]:
newParam = []
mode = 2
if newParam==[]:
    mode=2
    print("{} 정보 new 모드 {} ".format(DATANAME, mode))

공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황 정보 new 모드 2

In [6]:
resultDfMerged = pd.DataFrame()

In [7]:
import datetime

currentDateTime = datetime.datetime.now()
date = currentDateTime.date()
endYr = date.strftime("%Y")
endYr

'2022'

In [8]:
# 기준년도 산정
# 2007년 부터 데이터 존재하나, 1990년부터 수행
startYr = "1990"
dateRange = list(map(int,pd.period_range(startYr,endYr,freq='Y').strftime('%Y').tolist()))
# dateRange

In [9]:
resultDf = pd.DataFrame()
pageList = [] # 4/28 추가
APICALL = 0 #4/28 추가
for i  in dateRange:
    print(i)
    BASEPARAM={"serviceKey":APIKEY[0],"searchSrYr1": str(i), "searchSrYr2": str(i-1), "searchSrYr3": str(i-2),"type":"json"}
    scrapyResult = cf.scrapy(URL,SITENAME,DATANAME,SERVICENAME,BASEPARAM,PAGEYN, APIKEY,APICALL, JSONKEY, DUMMY)
    resultDf = scrapyResult[0]
    pageList.append( scrapyResult[1] )
    APICALL = scrapyResult[2]
    if resultDf.empty: # 정상 데이터가 없는 경우
            print("No Data")
    else:
        resultDfMerged = resultDfMerged.append(resultDf)

1990
1 page scraping start apicall iter: 1 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1990', 'searchSrYr2': '1989', 'searchSrYr3': '1988', 'type': 'json'} rows: 0 completed
No Data
1991
1 page scraping start apicall iter: 2 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1991', 'searchSrYr2': '1990', 'searchSrYr3': '1989', 'type': 'json'} rows: 0 completed
No Data
1992
1 page scraping start apicall iter: 3 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1992', 'searchSrYr2': '1991', 'searchSrYr3': '1990', 'type': 'json'} rows: 0 completed
No Data
1993
1 page scraping start apicall iter: 4 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1993', 'searchSrYr2': '1992', 'searchSrYr3': '1991', 'type': 'json'} rows: 0 completed
No Data
1994
1 page scraping start apicall iter: 5 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1994', 'searchSrYr2': '1993', 'searchSrYr3': '1992', 'type': 'json'} rows: 0 completed
No Data
1995
1 page scraping start apicall iter: 6 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1995', 'searchSrYr2': '1994', 'searchSrYr3': '1993', 'type': 'json'} rows: 0 completed
No Data
1996
1 page scraping start apicall iter: 7 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1996', 'searchSrYr2': '1995', 'searchSrYr3': '1994', 'type': 'json'} rows: 0 completed
No Data
1997
1 page scraping start apicall iter: 8 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1997', 'searchSrYr2': '1996', 'searchSrYr3': '1995', 'type': 'json'} rows: 0 completed
No Data
1998
1 page scraping start apicall iter: 9 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '1998', 'searchSrYr2': '1997', 'searchSrYr3': '1996', 'type': 'json'} rows: 0 completed
No Data
1999
1 page scraping start apicall iter: 10 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '1999', 'searchSrYr2': '1998', 'searchSrYr3': '1997', 'type': 'json'} rows: 0 completed
No Data
2000
1 page scraping start apicall iter: 11 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2000', 'searchSrYr2': '1999', 'searchSrYr3': '1998', 'type': 'json'} rows: 0 completed
No Data
2001
1 page scraping start apicall iter: 12 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2001', 'searchSrYr2': '2000', 'searchSrYr3': '1999', 'type': 'json'} rows: 0 completed
No Data
2002
1 page scraping start apicall iter: 13 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2002', 'searchSrYr2': '2001', 'searchSrYr3': '2000', 'type': 'json'} rows: 0 completed
No Data
2003
1 page scraping start apicall iter: 14 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2003', 'searchSrYr2': '2002', 'searchSrYr3': '2001', 'type': 'json'} rows: 0 completed
No Data
2004
1 page scraping start apicall iter: 15 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2004', 'searchSrYr2': '2003', 'searchSrYr3': '2002', 'type': 'json'} rows: 0 completed
No Data
2005
1 page scraping start apicall iter: 16 / used 0974320D-C689-4543-8464-10DE1E5505A9
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2005', 'searchSrYr2': '2004', 'searchSrYr3': '2003', 'type': 'json'} rows: 0 completed
No Data
2006
1 page scraping start apicall iter: 17 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
1 page is empty
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2006', 'searchSrYr2': '2005', 'searchSrYr3': '2004', 'type': 'json'} rows: 0 completed
No Data
2007
1 page scraping start apicall iter: 18 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2007', 'searchSrYr2': '2006', 'searchSrYr3': '2005', 'type': 'json'} rows: 26 completed
2008
1 page scraping start apicall iter: 19 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2008', 'searchSrYr2': '2007', 'searchSrYr3': '2006', 'type': 'json'} rows: 26 completed
2009
1 page scraping start apicall iter: 20 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2009', 'searchSrYr2': '2008', 'searchSrYr3': '2007', 'type': 'json'} rows: 26 completed
2010
1 page scraping start apicall iter: 21 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2010', 'searchSrYr2': '2009', 'searchSrYr3': '2008', 'type': 'json'} rows: 26 completed
2011
1 page scraping start apicall iter: 22 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2011', 'searchSrYr2': '2010', 'searchSrYr3': '2009', 'type': 'json'} rows: 26 completed
2012
1 page scraping start apicall iter: 23 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2012', 'searchSrYr2': '2011', 'searchSrYr3': '2010', 'type': 'json'} rows: 26 completed
2013
1 page scraping start apicall iter: 24 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2013', 'searchSrYr2': '2012', 'searchSrYr3': '2011', 'type': 'json'} rows: 26 completed
2014
1 page scraping start apicall iter: 25 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2014', 'searchSrYr2': '2013', 'searchSrYr3': '2012', 'type': 'json'} rows: 26 completed
2015
1 page scraping start apicall iter: 26 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2015', 'searchSrYr2': '2014', 'searchSrYr3': '2013', 'type': 'json'} rows: 26 completed
2016

1 page scraping start apicall iter: 27 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2016', 'searchSrYr2': '2015', 'searchSrYr3': '2014', 'type': 'json'} rows: 26 completed
2017
1 page scraping start apicall iter: 28 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2017', 'searchSrYr2': '2016', 'searchSrYr3': '2015', 'type': 'json'} rows: 26 completed
2018
1 page scraping start apicall iter: 29 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2018', 'searchSrYr2': '2017', 'searchSrYr3': '2016', 'type': 'json'} rows: 26 completed
2019
1 page scraping start apicall iter: 30 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2019', 'searchSrYr2': '2018', 'searchSrYr3': '2017', 'type': 'json'} rows: 26 completed
2020
1 page scraping start apicall iter: 31 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2020', 'searchSrYr2': '2019', 'searchSrYr3': '2018', 'type': 'json'} rows: 26 completed
2021
1 page scraping start apicall iter: 32 / used 0974320D-C689-4543-8464-10DE1E5505A9
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '0974320D-C689-4543-8464-10DE1E5505A9', 'searchSrYr1': '2021', 'searchSrYr2': '2020', 'searchSrYr3': '2019', 'type': 'json'} rows: 26 completed
2022
1 page scraping start apicall iter: 33 / used 49099D1D-E565-48E1-8A6F-D5F47135EA34
0 no pageNo
dataframe공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '49099D1D-E565-48E1-8A6F-D5F47135EA34', 'searchSrYr1': '2022', 'searchSrYr2': '2021', 'searchSrYr3': '2020', 'type': 'json'} rows: 26 completed

In [10]:
resultDfMerged

,jrsgvdpnm,bzorogcd,tojiarea1,tojiamt1,etcamt1,tojiarea2,tojiamt2,etcamt2,tojiarea3,tojiamt3,etcamt3,amtvariation,areavariation,etcvariation,tojiarea1rate,tojiamt1rate,etcamt1rate,tojiarea2rate,tojiamt2rate,etcamt2rate,tojiarea3rate,tojiamt3rate,etcamt3rate,amtvariationrate,areavariationrate,etcvariationrate
0,경상남도,B00015,3557600.00,278047810042,93056681527,0.000,0,0,0.00,0,0,278047810042,3557600.000,93056681527,2.23,1.24,3.32,0.00,0.00,0.00,0.00,0.00,0.00,2.780478e+13,355760000.0,9.305668e+12
1,인천광역시,B00004,5873594.20,1131382429749,66769190964,0.000,0,0,0.00,0,0,1131382429749,5873594.200,66769190964,3.67,5.06,2.38,0.00,0.00,0.00,0.00,0.00,0.00,1.131382e+14,587359420.0,6.676919e+12
2,경상북도,B00014,5192192.47,224915837848,53095042621,0.000,0,0,0.00,0,0,224915837848,5192192.470,53095042621,3.25,1.01,1.89,0.00,0.00,0.00,0.00,0.00,0.00,2.249158e+13,519219247.0,5.309504e+12
3,충청북도,B00010,2359368.20,96420299828,18613566132,0.000,0,0,0.00,0,0,96420299828,2359368.200,18613566132,1.48,0.43,0.66,0.00,0.00,0.00,0.00,0.00,0.00,9.642030e+12,235936820.0,1.861357e+12
4,경찰청,A00017,45574.00,18484843450,7214100,0.000,0,0,0.00,0,0,18484843450,45574.000,7214100,0.03,0.08,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.848484e+12,4557400.0,7.214100e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30,교육부,A00028,0.00,0,0,51881.600,25307101780,48765000,111575.00,59927603610,514739265,-25307101780,-51881.600,-48765000,0.00,0.00,0.00,0.13,0.22,0.00,0.16,0.43,0.03,-1.000000e+02,-100.0,-1.000000e+02
31,경기도,B00008,0.00,0,0,0.000,0,0,2985205.53,1060878289523,90592326267,0,0.000,0,0.00,0.00,0.00,0.00,0.00,0.00,4.19,7.68,5.61,0.000000e+00,0.0,0.000000e+00
32,대구광역시,B00003,0.00,0,0,1400973.000,296693217609,31330395866,849883.00,383196367077,46388831429,-296693217609,-1400973.000,-31330395866,0.00,0.00,0.00,3.64,2.57,3.18,1.19,2.77,2.87,-1.000000e+02,-100.0,-1.000000e+02
33,기상청,A00042,0.00,0,0,3206.000,2002753750,0,0.00,0,0,-2002753750,-3206.000,0,0.00,0.00,0.00,0.01,0.02,0.00,0.00,0.00,0.00,-1.000000e+02,-100.0,0.000000e+00
34,전라북도,B00012,0.00,0,0,478931.224,49414648468,8229890510,2566518.00,148995507856,29118487337,-49414648468,-478931.224,-8229890510,0.00,0.00,0.00,1.24,0.43,0.84,3.60,1.08,1.80,-1.000000e+02,-100.0,-1.000000e+02

In [10]:
cf.savedata(resultDfMerged, SITENAME,DATANAME,SERVICENAME,mode)

공공용지 취득실적-기관별 취득면적 및 보상액 기준 실적 현황 save compled

In [11]:
resultDfMerged.shape

(647, 26)

In [12]:
# 파라미터 저장 : 요청 키가 없는 API이므로, pageList만 저장

# 기존사용된 파라미터 정보에 추가 파라미터 append 후 저장
# ptlcmnoList = orgParam + ptlcmnoList
# 파라미터 없는경우 ptlcmnoList = []
ptlcmnoList = []
paramList = [ptlcmnoList,pageList]
# # 최종 파라미터 저장
cf.saveparam(paramList, SITENAME,DATANAME,SERVICENAME)