# 공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황

In [1]:
from common import commonFunc as cf
import pandas as pd
pd.set_option('display.max_columns', None)
metadata = pd.read_excel("../input/datalake_meta22.xlsx")

SITENAME = "건설사업정보시스템"
DATANAME= "공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황"
APIKEY = "1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF"

targetData = metadata.loc[metadata.자료명==DATANAME]
preSetFolder = targetData["저장폴더"].values[0]

preSetFolder

'../output/건설사업정보시스템/공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황/selectIoLcBlnOrByRwList.csv'

In [2]:
targetData = metadata.loc[metadata.자료명==DATANAME]

##### 파라미터 설정 #####
URL = targetData["URL"].values[0]
SERVICENAME = targetData["서비스키"].values[0]
SERVICENAME = SERVICENAME.split(".")[0]
REQPARAM = targetData["요청변수"].values[0]
REQPARAM = REQPARAM.split(",")
PRIMARYKEY = targetData["기본키"].values[0]

In [3]:
JSONKEY = "items"
DUMMY = 0

In [4]:
#### 페이지번호 설정 ###
PAGEYN=1
if REQPARAM.count("pageyn") == 0:
    PAGEYN = 0
else:
    PAGEYN = 1

In [5]:
resultDfMerged = pd.DataFrame()

In [6]:
import datetime

currentDateTime = datetime.datetime.now()
date = currentDateTime.date()
endYr = date.strftime("%Y")
endYr

'2022'

In [7]:
# 기준년도 산정
# 2007년 부터 데이터 존재하나, 1990년부터 수행
startYr = "1990"
dateRange = list(map(int,pd.period_range(startYr,endYr,freq='Y').strftime('%Y').tolist()))
# dateRange

In [8]:
resultDf = pd.DataFrame()
for i  in dateRange:
    print(i)
    BASEPARAM={"serviceKey":APIKEY,"searchSrYr1": str(i), "searchSrYr2": str(i-1), "searchSrYr3": str(i-2),"type":"json"}
    resultDf = cf.scrapy(URL,SITENAME,DATANAME,SERVICENAME,BASEPARAM,PAGEYN, JSONKEY, DUMMY)
    if resultDf.empty: # 정상 데이터가 없는 경우
            print("No Data")
    else:
        resultDfMerged = resultDfMerged.append(resultDf)

1990
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1990', 'searchSrYr2': '1989', 'searchSrYr3': '1988', 'type': 'json'} rows: 0 completed
No Data
1991
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1991', 'searchSrYr2': '1990', 'searchSrYr3': '1989', 'type': 'json'} rows: 0 completed
No Data
1992
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1992', 'searchSrYr2': '1991', 'searchSrYr3': '1990', 'type': 'json'} rows: 0 completed
No Data
1993
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1993', 'searchSrYr2': '1992', 'searchSrYr3': '1991', 'type': 'json'} rows: 0 completed
No Data
1994
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1994', 'searchSrYr2': '1993', 'searchSrYr3': '1992', 'type': 'json'} rows: 0 completed
No Data
1995
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1995', 'searchSrYr2': '1994', 'searchSrYr3': '1993', 'type': 'json'} rows: 0 completed
No Data
1996
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1996', 'searchSrYr2': '1995', 'searchSrYr3': '1994', 'type': 'json'} rows: 0 completed
No Data
1997
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1997', 'searchSrYr2': '1996', 'searchSrYr3': '1995', 'type': 'json'} rows: 0 completed
No Data
1998
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1998', 'searchSrYr2': '1997', 'searchSrYr3': '1996', 'type': 'json'} rows: 0 completed
No Data
1999
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '1999', 'searchSrYr2': '1998', 'searchSrYr3': '1997', 'type': 'json'} rows: 0 completed
No Data
2000
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2000', 'searchSrYr2': '1999', 'searchSrYr3': '1998', 'type': 'json'} rows: 0 completed
No Data
2001
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2001', 'searchSrYr2': '2000', 'searchSrYr3': '1999', 'type': 'json'} rows: 0 completed
No Data
2002
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2002', 'searchSrYr2': '2001', 'searchSrYr3': '2000', 'type': 'json'} rows: 0 completed
No Data
2003
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2003', 'searchSrYr2': '2002', 'searchSrYr3': '2001', 'type': 'json'} rows: 0 completed
No Data
2004
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2004', 'searchSrYr2': '2003', 'searchSrYr3': '2002', 'type': 'json'} rows: 0 completed
No Data
2005
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2005', 'searchSrYr2': '2004', 'searchSrYr3': '2003', 'type': 'json'} rows: 0 completed
No Data
2006
1 page scraping start
Empty DataFrame
Columns: []
Index: []
1 page is empty
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2006', 'searchSrYr2': '2005', 'searchSrYr3': '2004', 'type': 'json'} rows: 0 completed
No Data
2007
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2007', 'searchSrYr2': '2006', 'searchSrYr3': '2005', 'type': 'json'} rows: 27 completed
2008
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2008', 'searchSrYr2': '2007', 'searchSrYr3': '2006', 'type': 'json'} rows: 27 completed
2009
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2009', 'searchSrYr2': '2008', 'searchSrYr3': '2007', 'type': 'json'} rows: 27 completed
2010
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2010', 'searchSrYr2': '2009', 'searchSrYr3': '2008', 'type': 'json'} rows: 27 completed
2011
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2011', 'searchSrYr2': '2010', 'searchSrYr3': '2009', 'type': 'json'} rows: 27 completed
2012
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2012', 'searchSrYr2': '2011', 'searchSrYr3': '2010', 'type': 'json'} rows: 27 completed
2013
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2013', 'searchSrYr2': '2012', 'searchSrYr3': '2011', 'type': 'json'} rows: 27 completed
2014
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2014', 'searchSrYr2': '2013', 'searchSrYr3': '2012', 'type': 'json'} rows: 27 completed
2015
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2015', 'searchSrYr2': '2014', 'searchSrYr3': '2013', 'type': 'json'} rows: 27 completed
2016
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2016', 'searchSrYr2': '2015', 'searchSrYr3': '2014', 'type': 'json'} rows: 27 completed
2017
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2017', 'searchSrYr2': '2016', 'searchSrYr3': '2015', 'type': 'json'} rows: 27 completed
2018
1 page scraping start

Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2018', 'searchSrYr2': '2017', 'searchSrYr3': '2016', 'type': 'json'} rows: 27 completed
2019
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2019', 'searchSrYr2': '2018', 'searchSrYr3': '2017', 'type': 'json'} rows: 27 completed
2020
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2020', 'searchSrYr2': '2019', 'searchSrYr3': '2018', 'type': 'json'} rows: 27 completed
2021
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2021', 'searchSrYr2': '2020', 'searchSrYr3': '2019', 'type': 'json'} rows: 27 completed
2022
1 page scraping start
Empty DataFrame
Columns: []
Index: []
0 no pageNo
dataframe공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황, param:{'serviceKey': '1EFCBE0D-3203-4485-A7BA-5F5DB2B476BF', 'searchSrYr1': '2022', 'searchSrYr2': '2021', 'searchSrYr3': '2020', 'type': 'json'} rows: 27 completed

In [9]:
resultDfMerged

,jrsgvdpnm,orogcd,groupid,tojiarea1,tojiamt1,etcamt1,tojiarea2,tojiamt2,etcamt2,tojiarea3,tojiamt3,etcamt3,areavariation,amtvariation,etcvariation,tojiarea1rate,tojiamt1rate,etcamt1rate,tojiarea2rate,tojiamt2rate,etcamt2rate,tojiarea3rate,tojiamt3rate,etcamt3rate,amtvariationrate,areavariationrate,etcvariationrate
0,서울지방국토관리청,D00001,0,1986464.0,297308531298,19731955944,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0.000000e+00,1.986464e+06,297308531298,19731955944,1.24,1.33,0.70,0.00,0.00,0.00,0.00,0.00,0.00,2.973085e+13,198646400.0,1.973196e+12
1,원주지방국토관리청,D00002,0,5093585.0,38962447900,10295480020,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0.000000e+00,5.093585e+06,38962447900,10295480020,3.19,0.17,0.37,0.00,0.00,0.00,0.00,0.00,0.00,3.896245e+12,509358500.0,1.029548e+12
2,대전지방국토관리청,D00003,0,2275498.0,110027023780,13695596027,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0.000000e+00,2.275498e+06,110027023780,13695596027,1.42,0.49,0.49,0.00,0.00,0.00,0.00,0.00,0.00,1.100270e+13,227549800.0,1.369560e+12
3,익산지방국토관리청,D00004,0,3215670.0,75440123230,19742258660,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0.000000e+00,3.215670e+06,75440123230,19742258660,2.01,0.34,0.70,0.00,0.00,0.00,0.00,0.00,0.00,7.544012e+12,321567000.0,1.974226e+12
4,부산지방국토관리청,D00005,0,3196111.0,195293208255,40988902366,0.000000e+00,0,0,0.000000e+00,0.000000e+00,0.000000e+00,3.196111e+06,195293208255,40988902366,2.00,0.87,1.46,0.00,0.00,0.00,0.00,0.00,0.00,1.952932e+13,319611100.0,4.098890e+12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78,경상남도,B00015,0,0.0,0,0,6.259000e+03,4301038100,244062286,2.818254e+06,4.236835e+11,6.147686e+10,-6.259000e+03,-4301038100,-244062286,0.00,0.00,0.00,0.02,0.04,0.02,3.95,3.07,3.81,-1.000000e+02,-100.0,-1.000000e+02
79,제주특별자치도,B00016,0,0.0,0,0,0.000000e+00,0,0,1.264730e+06,2.958033e+11,1.402068e+10,0.000000e+00,0,0,0.00,0.00,0.00,0.00,0.00,0.00,1.77,2.14,0.87,0.000000e+00,0.0,0.000000e+00
80,세종특별자치시,B00017,0,0.0,0,0,0.000000e+00,0,0,5.846010e+05,1.117928e+11,8.033417e+09,0.000000e+00,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.82,0.81,0.50,0.000000e+00,0.0,0.000000e+00
81,시도 소 계,None,1,0.0,0,0,1.037379e+07,2335274595054,208433038656,3.151582e+07,5.729538e+12,6.579536e+11,-1.037379e+07,-2335274595054,-208433038656,0.00,0.00,0.00,26.97,20.20,21.18,44.20,41.49,40.74,-1.000000e+02,-100.0,-1.000000e+02
82,총 계,None,3,0.0,0,0,3.847000e+07,11559740849440,983982565090,7.130932e+07,1.381049e+13,1.614892e+12,-3.847000e+07,-11559740849440,-983982565090,0.00,0.00,0.00,100.00,100.00,100.00,100.00,100.00,100.00,-1.000000e+02,-100.0,-1.000000e+02

In [10]:
cf.savedata(resultDfMerged, SITENAME,DATANAME,SERVICENAME)

공공용지 취득실적-소속 기관별 취득면적 및 보상액 기준 실적 현황 save compled

In [11]:
resultDfMerged.shape

(1676, 27)